#pragma once

#define ISLAND_CHATTER_VERSION_MAJOR 1
#define ISLAND_CHATTER_VERSION_MINOR 0
#define ISLAND_CHATTER_VERSION_BUG 1
#define ISLAND_CHATTER_VERSION_STAGE 0
#define ISLAND_CHATTER_VERSION_BUILD 1

// PF_VERSION(1, 0, 1, PF_Stage_DEVELOP, 1)
#define ISLAND_CHATTER_AE_VERSION 526337

// PF_OutFlag_AUDIO_FLOAT_ONLY | PF_OutFlag_AUDIO_EFFECT_ONLY.
// AE's built-in Tone effect supplies the source sound object on text layers.
#define ISLAND_CHATTER_OUT_FLAGS -2013265920
#define ISLAND_CHATTER_OUT_FLAGS_2 0
